In [5]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr)

[[ 1  2  3]
 [ 6  8  9]
 [ 4  5  0]
 [11 23 45]]


In [9]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [11]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.shape)

(4, 3)


In [13]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.strides)

(12, 4)


In [15]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.ndim)

2


In [17]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.data)

In [19]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.itemsize)

4


In [21]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.base)

None


In [23]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.nbytes)

48


In [25]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.T)

[[ 1  6  4 11]
 [ 2  8  5 23]
 [ 3  9  0 45]]


In [27]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.real)

[[ 1  2  3]
 [ 6  8  9]
 [ 4  5  0]
 [11 23 45]]


In [29]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr.imag)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr)

[[ 1  2  3]
 [ 6  8  9]
 [ 4  5  0]
 [11 23 45]]


In [5]:
import numpy as np
arr=np.array([[1,2,3],[6,8,9],[4,5,0],[11,23,45]])
print(arr)

[[ 1  2  3]
 [ 6  8  9]
 [ 4  5  0]
 [11 23 45]]


In [53]:
import numpy as np
x=1+2*1j
C=np.zeros((2,2),dtype=np.complex_)
c=np.array([[0.+0.j,0.+0.j],
         [0.+0.j,0.+0.j]])
c[0,0]=1+1j+x
#d=np.array([[2.+3.j,0.+0.j],[0+0.j,0+0.j]])
print(C)
print(c)
#print(d)

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
[[2.+3.j 0.+0.j]
 [0.+0.j 0.+0.j]]
